### ISSUE TITLE
Design amend requests

### ISSUE THREAD

**Issue by pauldykeadestra** [AdestraDigitalDesign/DigitalDesign#1]
Header. Please insert one monochrome adestra logo top left. Smaller. Header bar to be 40px
Increase size of 'tell us about your project' and make a link.
Digital Design Team banner to be 120px high. Colour: #898989
Add icon to menus and increase font size.
Check background colour of tiles is #e0e0e0
Change colours of tiles to be #4f91cd, #fab625, #c31230 and #acacac.
Add a vertical line to separate the sidebar or make the page white and just the tiles area to be gray.

**Comment by AdestraTom** [comment]
Done. Changes committed to master branch and synced with remote repo
